services:
  - type: web
    name: d-cont-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DCONT_ADMIN_USERNAME
        sync: false
      - key: DCONT_ADMIN_PASSWORD
        sync: false
      - key: DCONT_ADMIN_MOBILE
        sync: false
